spring.application.name=chores

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000


# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.com.narvalo.finances=DEBUG
logging.level.org.springframework.web=DEBUG

# Server Configuration
server.port=8080

spring.security.user.name=myuser
spring.security.user.password=mypassword